---
- name: Apply Ansible Playbook
  become: true
  hosts: localhost
  tasks:
    - name: Include Terraform variables
      include_vars:
        dir: vars
        extensions:
          - yaml
          - yml

    - name: Deploy CloudWatch Agent
      include_tasks: tasks/install-cloud-watch-agent.yml
