---
- name: Apply Ansible Playbook
  become: true
  hosts: localhost
  tasks:
    - name: Include Terraform variables
      include_vars:
        dir: vars
        extensions:
          - yaml
          - yml

    - name: Distribution
      debug: msg="{{ ansible_distribution }}"

    - name: Deploy CloudWatchAgent Linux/Amazon
      include_tasks: linux-cloud-watch-setup.yml
      when: ansible_distribution == "Amazon"
