---
- name: Apply Ansible Playbook
  become: true
  hosts: localhost
  tasks:
    - name: Include Terraform variables
      include_vars:
        dir: vars
        extensions:
          - yaml
          - yml

    - include: linux-cloud-watch-setup.yml
    when: ansible_distribution == "Linux"
